# 当前项目application.yml 会覆盖掉依赖项目的application.yml 文件。
server:
  port: 8082
  context-path: /syerp/android
spring:
  datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.20:1521:ORCL
        username: BASE_ERP
        password: BASE_ERP
        tomcat:
          max-wait: 6000
          max-active: 30
          min-idle: 10
          test-on-borrow: true
          test-while-idle: true
          validation-query: select 1 from dual
          time-between-eviction-runs-millis: 300000
          min-evictable-idle-time-millis: 1800000
          initial-size: 5
          max-idle: 10
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

#一些自定义的项目配置
MyProjectConfig:
  fileUploadPath: d:\upload #上传文件储存文件夹
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/gwy_db
#    username: postgres
#    password: root
#    tomcat:
#      max-wait: 6000
#      max-active: 30
#      min-idle: 10
#      test-on-borrow: true
#      test-while-idle: true
#      validation-query: SELECT 1
#      time-between-eviction-runs-millis: 300000
#      min-evictable-idle-time-millis: 1800000
#      initial-size: 5
#      max-idle: 10