spring:
  datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.0.20:1521:ORCL
        username: BASE_ERP
        password: BASE_ERP
        tomcat:
          max-wait: 6000
          max-active: 30
          min-idle: 10
          test-on-borrow: true
          test-while-idle: true
          validation-query: SELECT 1
          time-between-eviction-runs-millis: 300000
          min-evictable-idle-time-millis: 1800000
          initial-size: 5
          max-idle: 10