# 当前项目application.yml 会覆盖掉依赖项目的application.yml 文件。
server:
  port: 8081
  context-path: /syerp/businfo
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gwy_db
    username: postgres
    password: root
    tomcat:
      max-wait: 6000
      max-active: 30
      min-idle: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      initial-size: 5
      max-idle: 10